"""add timestamps

Revision ID: 63137ca8a92d
Revises: cb9350fa5d3a
Create Date: 2026-09-25 18:37:35.388379

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63137ca8a92d"
down_revision: Union[str, Sequence[str], None] = "cb9350fa5d3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journal_entries", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    op.drop_column("journal_entries", "updated_at")
    # ### end Alembic commands ###
